feat: Add Mimir Wallet
availproject/avail-staking-dashboard pull request #12
Opened 2024-09-13 15:13 UTC by jarvandev

- inject mimir sdk when app is launch
- re-build tx when sign transaction in mimir

2024-09-14 14:22 UTC, Leouarz requested changes
Thanks for the PR
Overall looks good to me and tests are ok, mostly the blocking call at the beginning needs to be changed then we can proceed with merging.

2024-09-14 14:22 UTC, Leouarz commented on package.json
> +  "resolutions": {
Would it be possible to not add resolutions ? Why add them in the first place ? Something we can update ?

2024-09-14 14:22 UTC, Leouarz commented on src/main.tsx
> +injectMimirIfNecessary().then(() => {
Let's not have this blocking call and inject it somewhere else like an effect or else

2024-09-18 03:36 UTC, jarvandev commented
- We fixed the issue with blocking call
- There are multiple versions of `@polkadot/*` in the project, so we use resolutions to lock the version of `@polkadot/*`, for this problem, you can see the `@polkadot/*` in `node_modules`

2024-09-18 03:38 UTC, jarvandev commented on src/main.tsx
> +injectMimirIfNecessary().then(() => {
We fixed the issue with blocking call

2024-09-18 03:38 UTC, jarvandev commented on package.json
> +  "resolutions": {
There are multiple versions of @polkadot/* in the project, so we use resolutions to lock the version of @polkadot/*, for this problem, you can see the @polkadot/* in node_modules

2024-09-18 09:25 UTC, Leouarz approved these changes

2024-09-18 09:46 UTC, merged